//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotaiProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDiary
    {
        public int DiaryId { get; set; }
        public int dEmployeeId { get; set; }
        public System.DateTime dDate { get; set; }
        public string dWeather { get; set; }
        public string dDiaryNote { get; set; }
        public int dWarehouseNameId { get; set; }
    
        public virtual tEmployee tEmployee { get; set; }
        public virtual tWarehouseName tWarehouseName { get; set; }
    }
}
