//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotaiProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tOrderPay
    {
        public int oPayId { get; set; }
        public int oOrderId { get; set; }
        public int oOrderInstallment { get; set; }
        public int oPayType { get; set; }
        public decimal oPayment { get; set; }
        public System.DateTime oPayDate { get; set; }
    
        public virtual tOrder tOrder { get; set; }
        public virtual tOrderPayType tOrderPayType { get; set; }
    }
}
