//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotaiProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPromotionDetail
    {
        public int pDetailId { get; set; }
        public int pPromotionId { get; set; }
        public int pPromotionProductId { get; set; }
        public Nullable<int> pPromotionImageId { get; set; }
        public string pPromotionStartDate { get; set; }
        public string pPromotionTime { get; set; }
    
        public virtual tProduct tProduct { get; set; }
        public virtual tPromotion tPromotion { get; set; }
        public virtual tPromotionImage tPromotionImage { get; set; }
    }
}
