//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotaiProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tProduct()
        {
            this.tFavorites = new HashSet<tFavorite>();
            this.tOrderDetails = new HashSet<tOrderDetail>();
            this.tProductImages = new HashSet<tProductImage>();
            this.tShipDetails = new HashSet<tShipDetail>();
            this.tStatus = new HashSet<tStatu>();
            this.tStockDetails = new HashSet<tStockDetail>();
            this.tTransfers = new HashSet<tTransfer>();
            this.tWarehouses = new HashSet<tWarehouse>();
        }
    
        public int ProductId { get; set; }
        public string pNumber { get; set; }
        public string pName { get; set; }
        public int pCategory { get; set; }
        public int pMaterial { get; set; }
        public int pSize { get; set; }
        public string pLxWxH { get; set; }
        public double pWeight { get; set; }
        public string pIntroduction { get; set; }
        public decimal pPrice { get; set; }
        public Nullable<int> pQty { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tFavorite> tFavorites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tOrderDetail> tOrderDetails { get; set; }
        public virtual tProductCategory tProductCategory { get; set; }
        public virtual tProductMaterial tProductMaterial { get; set; }
        public virtual tProductSize tProductSize { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tProductImage> tProductImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tShipDetail> tShipDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tStatu> tStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tStockDetail> tStockDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tTransfer> tTransfers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tWarehouse> tWarehouses { get; set; }
    }
}
