//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotaiProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tShipDetail
    {
        public int ShipDetailId { get; set; }
        public int ShipId { get; set; }
        public int sOrderDetailId { get; set; }
        public int sProductId { get; set; }
        public int sQuantity { get; set; }
        public int sWarehouseNameId { get; set; }
    
        public virtual tOrderDetail tOrderDetail { get; set; }
        public virtual tProduct tProduct { get; set; }
        public virtual tShipList tShipList { get; set; }
        public virtual tWarehouseName tWarehouseName { get; set; }
    }
}
