//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotaiProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tStockList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tStockList()
        {
            this.tStockDetails = new HashSet<tStockDetail>();
        }
    
        public int StockId { get; set; }
        public int sEmployeeId { get; set; }
        public int sStockSerialValue { get; set; }
        public string sVendor { get; set; }
        public string sVendorTel { get; set; }
        public System.DateTime sStockDate { get; set; }
        public string sStockNote { get; set; }
    
        public virtual tEmployee tEmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tStockDetail> tStockDetails { get; set; }
    }
}
