//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotaiProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tStockDetail
    {
        public int StockDetailId { get; set; }
        public int sStockId { get; set; }
        public int sProductId { get; set; }
        public decimal sCost { get; set; }
        public int sQuantity { get; set; }
        public int sWarehouseNameId { get; set; }
        public string sNote { get; set; }
    
        public virtual tProduct tProduct { get; set; }
        public virtual tStockList tStockList { get; set; }
        public virtual tWarehouseName tWarehouseName { get; set; }
    }
}
